apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate-job
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: migrator
          image: migrate/migrate
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
          args:
            - "-path=/migrations"
            - "-database=postgres://$(DB_USER):$(DB_PASSWORD)@postgres-service:5432/edtech?sslmode=disable"
            - "up"
          volumeMounts:
            - mountPath: /migrations
              name: migrations-volume
      restartPolicy: Never
      volumes:
        - name: migrations-volume
          configMap:
            name: db-migrations