apiVersion: v1
kind: Service
metadata:
  name: edtech-app-service
  labels:
    app: edtech-backend
spec:
  type: LoadBalancer
  selector:
    app: edtech-backend
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 8080
